title: "Shihlung Lai"
email: janchen0716@gmail.com
description: "Personal academic site of Shihlung Lai"
baseurl: "/mm-github-pages-starter"
url: "https://janchen39054460.github.io"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: "Shihlung Lai"
  avatar: "/assets/images/218769.jpg"
  bio: "Graduate student at National Taiwan University of Science and Technology"

markdown: kramdown
